export default JOBS = [
    {id: '1', title: 'Mobile App Development'},
    {id: '2', title: 'Web Development'},
    {id: '3', title: 'Push Ups'},
    {id: '4', title: 'Make Lunch'},
    {id: '5', title: 'Pray'},
    {id: '6', title: 'Walk the dog'},
    {id: '7', title: 'Do Laundry'},
    {id: '8', title: 'Meditate'},
    {id: '9', title: 'Journaling'},
    {id: '10', title: 'Read'},
    {id: '11', title: 'Weed garden'},
    {id: '12', title: 'Water plants'},
    {id: '13', title: 'Feed the dog'},
    {id: '14', title: 'Clean the bathroom'},
    {id: '15', title: 'Vacuum the carpet'},
]